# Generated by Django 5.2 on 2025-04-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_urlfield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='URLField',
            new_name='link',
        ),
    ]
